export const QUIPLASH_TOPICS = [
    "Fast Food",
    "Gifts",
    "Lottery",
    "Slogans",
    "Movies",
    "Superheroes",
    "Holidays",
    "School",
    "Workplace",
    "Animals",
    "Celebrities",
    "Politics",
    "Social Media",
    "Technology",
    "Sports",
    "Music",
    "History",
    "Science",
    "Space",
    "Relationships",
    "Parenting",
    "Travel",
    "Food",
    "Hobbies",
    "Fashion",
    "Weather",
    "Fairy Tales",
    "Cartoons",
    "Internet Memes",
    "Books",
    "TV Shows",
    "Video Games",
    "Health",
    "Fitness",
    "Shopping",
    "Cars",
    "Driving",
    "Etiquette",
    "Myths",
    "Urban Legends",
    "Cooking",
    "Home Improvement",
    "Art",
    "Crime",
    "Medicine",
    "Wildlife",
    "Pets",
    "Technology Fails",
    "Horror",
    "Fantasy",
    "Time Travel",
    "Aliens",
    "Mystery",
    "Vacation Spots",
    "Weddings",
    "Hobbies",
    "Disasters",
    "Internet Trends",
    "School Subjects",
    "Hygiene",
    "Shopping Malls",
    "Dreams",
    "Inventions",
    "Public Transport",
    "Holidays",
    "Virtual Reality",
    "Cryptocurrency",
    "Space Exploration",
    "Virtual Meetings",
    "Fitness Trends",
    "Environmental Issues",
    "Secret Organizations",
    "Dinosaurs",
    "Ghosts",
    "Mythical Creatures",
    "Alternate Realities",
    "Bad Habits",
    "Self-Help",
    "Quirky Phobias",
    "Street Food",
    "City Life",
    "Country Life",
    "Extreme Sports",
    "Wild Parties",
    "Luxury Items",
    "Time Capsules",
    "Futuristic Gadgets",
    "Urban Decay",
    "Steampunk",
    "Cyberpunk",
    "Martial Arts",
    "Famous Quotes",
    "Secret Agents",
    "Cloning",
    "Artificial Intelligence",
    "Robots",
    "Pirates",
    "Witches",
    "Vampires",
    "Zombies",
    "Lost Civilizations",
    "Conspiracy Theories",
    "Reality TV",
    "Comic Books",
    "Superstitions",
    "Magical Spells",
    "Haunted Houses",
    "Talking Animals",
    "Treasure Hunts",
    "Cursed Objects",
    "Wacky Inventions",
    "Mad Scientists",
    "Invisible Creatures",
    "Mermaids",
    "Space Pirates",
    "Mutants",
    "Dragon Taming",
    "Robot Rebellion",
    "Secret Portals",
    "Parallel Universes",
    "Wizard Duels",
    "Monster Hunters",
    "Space Cowboys",
    "Haunted Amusement Parks",
    "Alien Abductions",
    "Underground Cities",
    "Giant Monsters",
    "Flying Cars",
    "Time-Loop Scenarios",
    "Evil Clowns",
    "Mysterious Islands",
    "Epic Quests",
    "Magic Potions",
    "Underwater Kingdoms",
    "Supernatural Detectives",
    "Mythical Races",
    "Living Toys",
    "Genies",
    "Shape-Shifters",
    "Fairy Godmothers",
    "Talking Plants",
    "Alien Invasions",
    "Supervillains",
    "Ninjas",
    "Cryptids",
    "Parallel Dimensions",
    "Magical Beasts"
];
